### ISSUE TITLE
Removing a network interface of the node this code is running on

### ISSUE THREAD

**Issue by stephanlindauer** [dulltz/preemptible-address-controller#1]
hi @dulltz,
thanks for this project. i am currently trying to solve a similar issue. my problem is that if i run code like yours on the node that is supposed to get the external ip assigned i will end up not being able to talk to the google api anymore after i have removed the old network interface. can you explain how you got around this issue (if you did)?
thanks :)

**Comment by dulltz** [comment]
@stephanlindauer 
> my problem is that if i run code like yours on the node that is supposed to get the external ip assigned i will end up not being able to talk to the google api anymore after i have removed the old network interface

Yes, I also noticed the problem.
If you wait for a while in that state, the GCE instance will be able to speak Google API. This is a behavior of GCE and I think it can't be helped by me. 
In other word,  if you use my implementation, daily downtime will always occur...

Another better way is to use a DNS outside the cluster and deploy a custom controller that updates A record. http://www.doxsey.net/blog/kubernetes--the-surprisingly-affordable-platform-for-personal-projects
